// Tour data â€” stop names and audio file references match the generated TTS files.
// Audio files live in: audio/<Destination>/<Tour>/<filename>
// Bilingual Hakone tours have fileEs + fileEn per stop.

window.TOUR_DATA = {
  destinations: [
    {
      id: "welcome",
      name: "Bienvenidos a JapÃ³n",
      nameEn: "Welcome to Japan",
      tagline: "El primer dÃ­a â€” en camino a Hakone",
      taglineEn: "The first day â€” on the way to Hakone",
      accent: "oklch(0.52 0.12 55)", // warm amber
      tours: ["hakone-morning"],
      startDate: "2026-05-12T00:00:00",
      endDate:   "2026-05-12T12:00:00",
    },
    {
      id: "hakone",
      name: "Hakone",
      nameEn: "Hakone",
      tagline: "MontaÃ±as y aguas termales",
      taglineEn: "Mountains and hot springs",
      accent: "oklch(0.46 0.06 235)", // slate blue
      tours: ["hakone-full-loop"],
      startDate: "2026-05-12T12:00:00",
      endDate:   "2026-05-12T23:59:59",
    },
    {
      id: "tokyo",
      name: "Tokio",
      nameEn: "Tokyo",
      tagline: "Tres caminatas urbanas",
      taglineEn: "Three urban walks",
      accent: "oklch(0.52 0.11 28)", // soft crimson
      tours: ["shibuya", "asakusa", "shinjuku"],
      startDate: "2026-05-12T15:00:00",
      endDate:   "2026-05-15T23:59:59",
    },
    {
      id: "kyoto",
      name: "Kioto",
      nameEn: "Kyoto",
      tagline: "Templos y callejones",
      taglineEn: "Temples and lanes",
      accent: "oklch(0.45 0.07 155)", // mossy green
      tours: ["gion", "philosophers-path"],
      startDate: "2026-05-16T00:00:00",
      endDate:   "2026-05-20T23:59:59",
    },
  ],
  tours: {
    shibuya: {
      id: "shibuya",
      destination: "tokyo",
      name: "Caminata por Shibuya",
      nameEn: "Shibuya District Walk",
      blurb: "El corazÃ³n elÃ©ctrico de Tokio: cruces, callejones y luces de neÃ³n.",
      blurbEn: "Tokyo's electric heart: crossings, alleys, and neon.",
      languages: ["es"],
      audioDir: "Tokyo/Shibuya",
      photo: "images/shibuya-crossing.jpg",
      stops: [
        { photo: "images/shibuya-crossing.jpg",   name: "IntroducciÃ³n",         nameEn: "Introduction",             desc: "Bienvenidos al distrito de Shibuya.",              descEn: "Welcome to Shibuya district.",                   file: "01_Shibuya_Introduccion.mp3" },
        { photo: "images/scramble-square.jpg", name: "Scramble Square", nameEn: "Scramble Square", desc: "La torre mÃ¡s nueva sobre el cruce mÃ¡s famoso.", descEn: "The newest tower over the most famous crossing.", file: "02_Shibuya_Scramble_Square.mp3" },
        { photo: "images/hachiko.jpg",                                           name: "Estatua de HachikÅ",   nameEn: "HachikÅ Statue",           desc: "El punto de encuentro mÃ¡s famoso de JapÃ³n.",      descEn: "Japan's most famous meeting point.",              file: "03_Shibuya_Estatua_Hachiko.mp3" },
        { photo: "images/shibuya-crossing.jpg",   name: "Cruce de Shibuya",     nameEn: "Shibuya Scramble Crossing", desc: "Un mar de personas cada cambio de luz.",         descEn: "A sea of people every light change.",             file: "04_Shibuya_Cruce_Shibuya.mp3" },
        { photo: "images/shibuya-109.jpg",                          name: "Shibuya 109",          nameEn: "Shibuya 109",              desc: "Moda joven y tendencias en ocho pisos.",          descEn: "Youth fashion and trends across eight floors.",   file: "05_Shibuya_109.mp3" },
        { photo: null,                                                                                                                                  name: "Center Gai",           nameEn: "Center Gai",               desc: "Calle peatonal llena de tiendas y mÃºsica.",       descEn: "Pedestrian street full of shops and music.",      file: "06_Shibuya_Center_Gai.mp3" },
        { photo: null,                                                                                                                                  name: "Mandarake",            nameEn: "Mandarake",                desc: "El paraÃ­so del manga y el anime retro.",          descEn: "Paradise for manga and retro anime.",             file: "07_Shibuya_Mandarake.mp3" },
        { photo: "images/omotesando.jpg", name: "KÅen-dÅri",            nameEn: "KÅen-dÅri",                desc: "La avenida que sube hacia el parque.",            descEn: "The avenue rising toward the park.",              file: "08_Shibuya_Koen_Dori.mp3" },
        { photo: "images/yoyogi-park.jpg", name: "Parque Yoyogi", nameEn: "Yoyogi Park", desc: "Refugio verde junto al santuario Meiji.", descEn: "Green refuge next to Meiji Shrine.", file: "09_Shibuya_Parque_Yoyogi.mp3" },
        { photo: "images/omotesando.jpg", name: "OmotesandÅ",           nameEn: "OmotesandÅ",               desc: "La avenida arbolada de las marcas.",              descEn: "The tree-lined luxury avenue.",                   file: "10_Shibuya_Omotesando.mp3" },
        { photo: null,                                                                                                                                  name: "Calle Takeshita",      nameEn: "Takeshita Street",         desc: "Moda juvenil, crepas y colores.",                 descEn: "Youth fashion, crepes, and colors.",               file: "11_Shibuya_Calle_Takeshita.mp3" },
        { photo: "images/meiji-shrine.jpg",                    name: "Santuario Meiji",      nameEn: "Meiji Shrine",             desc: "Bosque sagrado en medio de la ciudad.",           descEn: "Sacred forest in the middle of the city.",         file: "12_Shibuya_Santuario_Meiji.mp3" },
      ],
    },
    asakusa: {
      id: "asakusa",
      destination: "tokyo",
      name: "Caminata por Asakusa",
      nameEn: "Asakusa District Walk",
      blurb: "El Tokio antiguo alrededor del templo SensÅ-ji.",
      blurbEn: "Old Tokyo around SensÅ-ji temple.",
      languages: ["es"],
      audioDir: "Tokyo/Asakusa",
      photo: "images/kaminarimon.jpg",
      stops: [
        { photo: "images/kaminarimon.jpg",        name: "IntroducciÃ³n",            nameEn: "Introduction",           desc: "Bienvenidos al barrio mÃ¡s antiguo de Tokio.",      descEn: "Welcome to Tokyo's oldest neighborhood.",          file: "01_Asakusa_Introduccion.mp3" },
        { photo: "images/kaminarimon.jpg",        name: "Centro de InformaciÃ³n",   nameEn: "Tourist Information",    desc: "Punto de partida y orientaciÃ³n.",                 descEn: "Starting point and orientation.",                  file: "02_Asakusa_Centro_Informacion.mp3" },
        { photo: "images/kaminarimon.jpg",        name: "Puerta Kaminarimon",      nameEn: "Kaminarimon Gate",       desc: "El gran farol rojo da la bienvenida.",            descEn: "The great red lantern welcomes you.",              file: "03_Asakusa_Puerta_Kaminarimon.mp3" },
        { photo: "images/sensoji.jpg",                                name: "Calle Nakamise",          nameEn: "Nakamise Street",        desc: "Puestos de dulces y recuerdos centenarios.",      descEn: "Centuries-old stalls of sweets and gifts.",        file: "04_Asakusa_Calle_Nakamise.mp3" },
        { photo: "images/sensoji.jpg",                                name: "Puerta HÅzÅmon",          nameEn: "HÅzÅmon Gate",           desc: "Guardianes de madera y enormes sandalias.",       descEn: "Wooden guardians and giant sandals.",              file: "05_Asakusa_Puerta_Hozomon.mp3" },
        { photo: "images/sensoji.jpg",                                name: "GojÅ«nÅ-tÅ",               nameEn: "Five-Story Pagoda",      desc: "Silueta clÃ¡sica contra el cielo.",                descEn: "Classic silhouette against the sky.",              file: "06_Asakusa_Gojunoto.mp3" },
        { photo: "images/sensoji.jpg",                                name: "Templo SensÅ-ji",         nameEn: "SensÅ-ji Temple",        desc: "El templo mÃ¡s antiguo de Tokio.",                 descEn: "Tokyo's oldest temple.",                           file: "07_Asakusa_Templo_Sensoji.mp3" },
        { photo: "images/asakusa-shrine.jpg",                 name: "Santuario Asakusa",       nameEn: "Asakusa Shrine",         desc: "Honor a los pescadores que fundaron el lugar.",   descEn: "Honoring the fishermen who founded the site.",     file: "08_Asakusa_Santuario_Asakusa.mp3" },
        { photo: null,                                                                                                                                  name: "TeterÃ­a Suzukien",        nameEn: "Suzukien Tea House",     desc: "Matcha en siete grados de intensidad.",           descEn: "Matcha in seven grades of intensity.",             file: "09_Asakusa_Teteria_Suzukien.mp3" },
        { photo: null,                                                                                                                                  name: "Estatua DanjÅ«rÅ",         nameEn: "DanjÅ«rÅ Statue",         desc: "Leyenda del teatro kabuki.",                      descEn: "Legend of kabuki theater.",                        file: "10_Asakusa_Estatua_Danjuro.mp3" },
        { photo: "images/hanayashiki.jpg", name: "Hanayashiki",           nameEn: "Hanayashiki",            desc: "El parque de atracciones mÃ¡s antiguo de JapÃ³n.", descEn: "Japan's oldest amusement park.",                    file: "11_Asakusa_Hanayashiki.mp3" },
      ],
    },
    shinjuku: {
      id: "shinjuku",
      destination: "tokyo",
      name: "Caminata por Shinjuku",
      nameEn: "Shinjuku Walk",
      blurb: "Rascacielos de dÃ­a, callejones de neÃ³n de noche.",
      blurbEn: "Skyscrapers by day, neon alleys by night.",
      languages: ["es"],
      audioDir: "Tokyo/Shinjuku",
      photo: "images/tokyo-metro-gov.jpg",
      stops: [
        { photo: "images/tokyo-metro-gov.jpg", name: "IntroducciÃ³n",          nameEn: "Introduction",                   desc: "La estaciÃ³n mÃ¡s concurrida del mundo.",          descEn: "The world's busiest station.",                  file: "01_Shinjuku_Introduccion.mp3" },
        { photo: "images/tokyo-metro-gov.jpg", name: "Gobierno Metropolitano", nameEn: "Metropolitan Government Bldg.", desc: "Mirador gratuito al piso 45.",                  descEn: "Free observation deck on floor 45.",            file: "02_Shinjuku_Gobierno_Metropolitano.mp3" },
        { photo: null,                                                                                                                                  name: "Omoide YokochÅ",        nameEn: "Omoide YokochÅ",                 desc: "Humo de yakitori y luces amarillas.",            descEn: "Yakitori smoke and yellow lights.",             file: "03_Shinjuku_Omoide_Yokocho.mp3" },
        { photo: null,                                                                                                                                  name: "Cabeza de Godzilla",    nameEn: "Godzilla Head",                  desc: "El monstruo asoma entre los edificios.",        descEn: "The monster peers between buildings.",          file: "04_Shinjuku_Cabeza_Godzilla.mp3" },
        { photo: "images/hanazono-shrine.jpg",            name: "Santuario Hanazono",    nameEn: "Hanazono Shrine",                desc: "Calma en medio del bullicio.",                  descEn: "Calm in the middle of the bustle.",             file: "05_Shinjuku_Santuario_Hanazono.mp3" },
        { photo: "images/golden-gai.jpg",               name: "Golden Gai",            nameEn: "Golden Gai",                     desc: "Bares diminutos en seis callejones.",            descEn: "Tiny bars across six alleys.",                  file: "06_Shinjuku_Golden_Gai.mp3" },
        { photo: null,                                                                                                                                  name: "Museo del SamurÃ¡i",     nameEn: "Samurai Museum",                 desc: "Armaduras y katanas del JapÃ³n feudal.",         descEn: "Armors and katanas of feudal Japan.",           file: null },
        { photo: null,                                                                                                                                  name: "JardÃ­n Shinjuku Gyoen", nameEn: "Shinjuku Gyoen",                 desc: "Tres jardines en uno: japonÃ©s, francÃ©s, inglÃ©s.",descEn: "Three gardens in one: Japanese, French, English.", file: null },
      ],
    },
    gion: {
      id: "gion",
      destination: "kyoto",
      name: "Caminata por Gion",
      nameEn: "Gion District Walk",
      blurb: "El distrito de las geishas, faroles y casas de tÃ©.",
      blurbEn: "The geisha district â€” lanterns and teahouses.",
      languages: ["es"],
      audioDir: "Kyoto/Gion",
      photo: "images/gion.jpg",
      stops: [
        { photo: "images/gion.jpg",  name: "IntroducciÃ³n",          nameEn: "Introduction",          desc: "Bienvenidos al corazÃ³n histÃ³rico de Kioto.",      descEn: "Welcome to Kyoto's historic heart.",              file: "01_Gion_Introduccion.mp3" },
        { photo: "images/minamiza.jpg",                    name: "Teatro Minamiza",       nameEn: "Minamiza Theatre",      desc: "El teatro kabuki mÃ¡s antiguo de JapÃ³n.",          descEn: "Japan's oldest kabuki theater.",                   file: "02_Gion_Teatro_Minamiza.mp3" },
        { photo: "images/gion.jpg",  name: "CallejÃ³n Shirakawa",    nameEn: "Shirakawa Lane",        desc: "Sauces, puentes y casas de madera.",              descEn: "Willows, bridges, and wooden houses.",             file: "03_Gion_Callejon_Shirakawa.mp3" },
        { photo: "images/gion.jpg",  name: "Puente Tatsumi",        nameEn: "Tatsumi Bridge",        desc: "El puente mÃ¡s fotografiado de Gion.",             descEn: "Gion's most photographed bridge.",                 file: "04_Gion_Puente_Tatsumi.mp3" },
        { photo: null,                                                                                                                                  name: "Calle Shinmonzen",      nameEn: "Shinmonzen Street",     desc: "GalerÃ­as de arte y antigÃ¼edades.",                descEn: "Art galleries and antiques.",                      file: "05_Gion_Calle_Shinmonzen.mp3" },
        { photo: "images/ichiriki.jpg",                      name: "Casa de TÃ© Ichiriki",   nameEn: "Ichiriki Tea House",    desc: "La ochaya mÃ¡s famosa de Gion.",                  descEn: "Gion's most famous ochaya.",                       file: "06_Gion_Casa_Te_Ichiriki.mp3" },
        { photo: "images/gion.jpg",  name: "Calle HanamikÅji",      nameEn: "HanamikÅji Street",     desc: "La calle mÃ¡s fotografiada de Kioto.",             descEn: "Kyoto's most photographed street.",                file: "07_Gion_Calle_Hanamikoji.mp3" },
        { photo: "images/gion.jpg",  name: "Gion Corner",           nameEn: "Gion Corner",           desc: "Artes tradicionales en un solo teatro.",          descEn: "Traditional arts in one theater.",                 file: "08_Gion_Gion_Corner.mp3" },
        { photo: null,                                                                                                                                  name: "Santuario Yasui",       nameEn: "Yasui Shrine",          desc: "El santuario de los cortes y las uniones.",       descEn: "The shrine of cuts and bonds.",                    file: "09_Gion_Santuario_Yasui.mp3" },
        { photo: "images/kenninji.jpg", name: "Templo Kennin-ji", nameEn: "Kennin-ji Temple",      desc: "El templo zen mÃ¡s antiguo de Kioto.",             descEn: "Kyoto's oldest Zen temple.",                       file: "10_Gion_Templo_Kennin-ji.mp3" },
        { photo: null,                                                                                                                                  name: "Santuario Ebisu",       nameEn: "Ebisu Shrine",          desc: "Dios del comercio y la buena fortuna.",           descEn: "God of commerce and good fortune.",                file: "11_Gion_Santuario_Ebisu.mp3" },
        { photo: null,                                                                                                                                  name: "Saryo Tsujiri",         nameEn: "Saryo Tsujiri",         desc: "Matcha y dulces japoneses desde 1860.",           descEn: "Matcha and Japanese sweets since 1860.",           file: "12_Gion_Saryo_Tsujiri.mp3" },
      ],
    },
    "philosophers-path": {
      id: "philosophers-path",
      destination: "kyoto",
      name: "Camino del FilÃ³sofo",
      nameEn: "Philosopher's Path",
      blurb: "Dos kilÃ³metros junto a un canal de cerezos.",
      blurbEn: "Two kilometers along a cherry-tree canal.",
      languages: ["es"],
      audioDir: "Kyoto/Filosofo",
      photo: "images/philosophers-walk.jpg",
      stops: [
        { photo: "images/philosophers-walk.jpg", name: "IntroducciÃ³n",       nameEn: "Introduction",          desc: "Bienvenidos al paseo mÃ¡s tranquilo de Kioto.",    descEn: "Welcome to Kyoto's most peaceful walk.",           file: "01_Filosofo_Introduccion.mp3" },
        { photo: "images/nanzenji.jpg",             name: "Templo Nanzen-ji",   nameEn: "Nanzen-ji Temple",      desc: "Una de las tres grandes puertas zen.",            descEn: "One of the three great Zen gates.",                file: "02_Filosofo_Templo_Nanzen-ji.mp3" },
        { photo: "images/eikando.jpg",                 name: "Templo Eikan-dÅ",    nameEn: "Eikan-dÅ Temple",       desc: "Famoso por sus arces en otoÃ±o.",                  descEn: "Famous for its autumn maples.",                    file: "03_Filosofo_Templo_Eikan-do.mp3" },
        { photo: "images/philosophers-walk.jpg", name: "Extremo Sur",        nameEn: "Southern End",          desc: "El punto de inicio del camino.",                  descEn: "The starting point of the path.",                  file: "04_Filosofo_Extremo_Sur.mp3" },
        { photo: null,                                                                                                                                                       name: "Santuario ÅŒtoyo",    nameEn: "ÅŒtoyo Shrine",          desc: "Guardado por ratones de piedra.",                 descEn: "Guarded by stone mice.",                           file: "05_Filosofo_Santuario_Otoyo.mp3" },
        { photo: null,                                                                                                                                                       name: "Puente Daitoyo",     nameEn: "Daitoyo Bridge",        desc: "Cruce tranquilo sobre el canal.",                 descEn: "Quiet crossing over the canal.",                   file: "06_Filosofo_Puente_Daitoyo.mp3" },
        { photo: "images/philosophers-walk.jpg", name: "Puente Sakurabashi", nameEn: "Sakurabashi Bridge",    desc: "El puente de los cerezos.",                       descEn: "The cherry blossom bridge.",                       file: "07_Filosofo_Puente_Sakurabashi.mp3" },
        { photo: "images/honenin.jpg",                                                     name: "Templo HÅnen-in",    nameEn: "HÅnen-in Temple",       desc: "Templo discreto cubierto de musgo.",              descEn: "A quiet, moss-covered temple.",                    file: "08_Filosofo_Templo_Honen-in.mp3" },
        { photo: "images/ginkakuji.jpg",                                      name: "Ginkaku-ji",         nameEn: "Ginkaku-ji",            desc: "El PabellÃ³n de Plata y su jardÃ­n de arena.",      descEn: "The Silver Pavilion and its sand garden.",         file: "09_Filosofo_Templo_Ginkaku-ji.mp3" },
      ],
    },
    "hakone-morning": {
      id: "hakone-morning",
      destination: "welcome",
      name: "Bienvenidos a JapÃ³n",
      nameEn: "Welcome to Japan",
      blurb: "El tren bala, la montaÃ±a y las primeras horas en JapÃ³n.",
      blurbEn: "The bullet train, the mountain, and the first hours in Japan.",
      languages: ["es", "en"],
      audioDir: "Hakone/Morning_Script",
      photo: "images/fuji-lake-ashi.jpg",
      stops: [
        { photo: "images/fuji-owakudani.jpg", name: "Bienvenidos a JapÃ³n",     nameEn: "Welcome to Japan",              desc: "El viaje comienza.",                              descEn: "The journey begins.",                          fileEs: "Morning_Ch01_ES_Bienvenidos_a_Japon.mp3",      fileEn: "Morning_Ch01_EN_Welcome_to_Japan.mp3" },
        { photo: "images/shinkansen.jpg",                                                                   name: "El Shinkansen",           nameEn: "The Shinkansen",                desc: "A bordo del tren bala.",                          descEn: "Aboard the bullet train.",                     fileEs: "Morning_Ch02_ES_El_Shinkansen.mp3",            fileEn: "Morning_Ch02_EN_The_Shinkansen.mp3" },
        { photo: "images/fuji-owakudani.jpg", name: "Por la Ventana",          nameEn: "Out the Window",                desc: "El paisaje que pasa a 300 km/h.",                 descEn: "The landscape flying by at 300 km/h.",         fileEs: "Morning_Ch03_ES_Por_la_Ventana.mp3",           fileEn: "Morning_Ch03_EN_Out_the_Window.mp3" },
        { photo: "images/odawara-castle.jpg",                                                                             name: "EstaciÃ³n Odawara",        nameEn: "Odawara Station",               desc: "Puerta de entrada a Hakone.",                     descEn: "Gateway to Hakone.",                           fileEs: "Morning_Ch04_ES_Estacion_Odawara.mp3",         fileEn: "Morning_Ch04_EN_Odawara_Station.mp3" },
        { photo: "images/hakone-tozan.jpg",                                                      name: "Los Cambios de VÃ­a",      nameEn: "The Switchbacks",               desc: "El tren de montaÃ±a sube en zigzag.",              descEn: "The mountain train climbs in zigzags.",        fileEs: "Morning_Ch05_ES_Los_Cambios_de_Via.mp3",       fileEn: "Morning_Ch05_EN_The_Switchbacks.mp3" },
        { photo: "images/hakone-openair.jpg",                                                                                   name: "El Funicular",            nameEn: "The Funicular",                 desc: "Ascenso hasta la cima de GÅra.",                  descEn: "Ascending to the top of GÅra.",                fileEs: "Morning_Ch06_ES_El_Funicular.mp3",             fileEn: "Morning_Ch06_EN_The_Funicular.mp3" },
        { photo: "images/owakudani.jpg",                       name: "TelefÃ©rico y Owakudani",  nameEn: "Ropeway and Owakudani",         desc: "Volamos hacia el valle volcÃ¡nico.",                descEn: "We fly toward the volcanic valley.",           fileEs: "Morning_Ch07_ES_Teleferico_y_Owakudani.mp3",   fileEn: "Morning_Ch07_EN_Ropeway_and_Owakudani.mp3" },
        { photo: "images/lake-ashi.jpg",                         name: "Lago Ashi y los Piratas", nameEn: "Lake Ashi Pirates",             desc: "Vista del Fuji si el dÃ­a estÃ¡ claro.",            descEn: "View of Fuji on a clear day.",                 fileEs: "Morning_Ch08_ES_Lago_Ashi_Piratas.mp3",        fileEn: "Morning_Ch08_EN_Lake_Ashi_Pirates.mp3" },
        { photo: "images/fuji-lake-ashi.jpg",                             name: "Ichigo Ichie",            nameEn: "Ichigo Ichie",                  desc: "Un momento Ãºnico, una vez en la vida.",           descEn: "One moment, one time in a lifetime.",          fileEs: "Morning_Ch09_ES_Ichigo_Ichie.mp3",             fileEn: "Morning_Ch09_EN_Ichigo_Ichie.mp3" },
      ],
    },
    "hakone-full-loop": {
      id: "hakone-full-loop",
      destination: "hakone",
      name: "Recorrido Completo",
      nameEn: "Full Loop",
      blurb: "El gran cÃ­rculo: tren, museos, templos y el TÅkaidÅ.",
      blurbEn: "The grand circle: train, museums, shrines, and the TÅkaidÅ.",
      languages: ["es", "en"],
      audioDir: "Hakone/Full_Loop",
      photo: "images/owakudani.jpg",
      stops: [
        { photo: "images/fuji-owakudani.jpg", name: "IntroducciÃ³n",                  nameEn: "Introduction",                      desc: "El gran recorrido de Hakone comienza.",           descEn: "Hakone's grand tour begins.",                  fileEs: "Loop_Ch01_ES_Introduccion.mp3",                        fileEn: "Loop_Ch01_EN_Introduction.mp3" },
        { photo: "images/odawara-castle.jpg",                                                                             name: "Odawara, Pueblo Castillo",      nameEn: "Odawara Castle Town",               desc: "La ciudad samurÃ¡i a los pies de Hakone.",         descEn: "The samurai city at Hakone's foot.",            fileEs: "Loop_Ch02_ES_Odawara_Pueblo_Castillo.mp3",             fileEn: "Loop_Ch02_EN_Odawara_Castle_Town.mp3" },
        { photo: "images/hakone-tozan.jpg",                                                      name: "Tren Tozan, Tramo Bajo",        nameEn: "Tozan Railway â€” Lower Leg",         desc: "El tren de montaÃ±a mÃ¡s famoso de JapÃ³n.",         descEn: "Japan's most famous mountain railway.",         fileEs: "Loop_Ch03_ES_Tren_Tozan_Tramo_Bajo.mp3",              fileEn: "Loop_Ch03_EN_Tozan_Railway_Lower.mp3" },
        { photo: "images/hakone-yumoto.jpg",                                    name: "Hakone Yumoto Onsen",           nameEn: "Hakone Yumoto Onsen",               desc: "Aguas termales a los pies de la montaÃ±a.",        descEn: "Hot springs at the mountain's foot.",           fileEs: "Loop_Ch04_ES_Hakone_Yumoto_Onsen.mp3",                fileEn: "Loop_Ch04_EN_Hakone_Yumoto_Onsen.mp3" },
        { photo: "images/hakone-tozan.jpg",                                                      name: "La Subida a la MontaÃ±a",        nameEn: "Mountain Climb",                    desc: "El tren zigzaguea hacia GÅra.",                   descEn: "The train zigzags up to GÅra.",                 fileEs: "Loop_Ch05_ES_La_Subida_Montana.mp3",                   fileEn: "Loop_Ch05_EN_Mountain_Climb.mp3" },
        { photo: "images/hakone-openair.jpg",                                                                                   name: "Museo al Aire Libre",           nameEn: "Open-Air Museum",                   desc: "Esculturas entre montaÃ±as.",                      descEn: "Sculptures among the mountains.",               fileEs: "Loop_Ch06_ES_Museo_Aire_Libre.mp3",                    fileEn: "Loop_Ch06_EN_Open_Air_Museum.mp3" },
        { photo: "images/hakone-openair.jpg",                                                                                   name: "GÅra, Pueblo Cima",             nameEn: "GÅra Summit Town",                  desc: "Final del tren, inicio del funicular.",           descEn: "End of train, start of funicular.",             fileEs: "Loop_Ch07_ES_Gora_Pueblo_Cima.mp3",                    fileEn: "Loop_Ch07_EN_Gora_Summit_Town.mp3" },
        { photo: "images/hakone-ropeway.jpg",                                        name: "Funicular GÅraâ€“SÅunzan",        nameEn: "Cable Car GÅraâ€“SÅunzan",            desc: "Cuatro minutos colgando sobre el bosque.",        descEn: "Four minutes hanging above the forest.",        fileEs: "Loop_Ch08_ES_Funicular_Gora_Sounzan.mp3",              fileEn: "Loop_Ch08_EN_Cable_Car_Gora_Sounzan.mp3" },
        { photo: "images/owakudani.jpg",                       name: "SÅunzan, Cima del Funicular",   nameEn: "SÅunzan â€” Top of Funicular",        desc: "El valle volcÃ¡nico se abre ante nosotros.",       descEn: "The volcanic valley opens before us.",          fileEs: "Loop_Ch09_ES_Sounzan_Cima_Funicular.mp3",              fileEn: "Loop_Ch09_EN_Sounzan_Top_Funicular.mp3" },
        { photo: "images/hakone-ropeway.jpg",                                        name: "TelefÃ©rico SÅunzanâ€“ÅŒwakudani",  nameEn: "Ropeway SÅunzanâ€“ÅŒwakudani",         desc: "Volamos sobre el humo sulfuroso.",                 descEn: "We fly over sulfurous steam.",                  fileEs: "Loop_Ch10_ES_Teleferico_Sounzan_Owakudani.mp3",        fileEn: "Loop_Ch10_EN_Ropeway_Sounzan_Owakudani.mp3" },
        { photo: "images/owakudani.jpg",                       name: "ÅŒwakudani, Gran Valle Hirviente", nameEn: "ÅŒwakudani â€” Great Boiling Valley", desc: "Cocidos en aguas sulfurosas, los huevos negros.", descEn: "Black eggs cooked in sulfurous waters.",        fileEs: "Loop_Ch11_ES_Owakudani_Gran_Valle_Hirviente.mp3",      fileEn: "Loop_Ch11_EN_Owakudani_Great_Boiling_Valley.mp3" },
        { photo: "images/hakone-ropeway.jpg",                                        name: "TelefÃ©rico ÅŒwakudaniâ€“Togendai", nameEn: "Ropeway ÅŒwakudaniâ€“Togendai",        desc: "Descendemos hacia el lago Ashi.",                 descEn: "We descend toward Lake Ashi.",                  fileEs: "Loop_Ch12_ES_Teleferico_Owakudani_Togendai.mp3",       fileEn: "Loop_Ch12_EN_Ropeway_Owakudani_Togendai.mp3" },
        { photo: "images/lake-ashi.jpg",                         name: "Togendai y el Lago Ashi",       nameEn: "Togendai and Lake Ashi",            desc: "El puerto a orillas del lago.",                   descEn: "The port on the lake's shore.",                 fileEs: "Loop_Ch13_ES_Togendai_Lago_Ashi.mp3",                  fileEn: "Loop_Ch13_EN_Togendai_Lake_Ashi.mp3" },
        { photo: "images/lake-ashi.jpg",                         name: "Los Barcos Pirata",             nameEn: "The Pirate Ships",                  desc: "Vista del Fuji si el dÃ­a estÃ¡ claro.",            descEn: "View of Fuji on a clear day.",                  fileEs: "Loop_Ch14_ES_Los_Barcos_Pirata.mp3",                   fileEn: "Loop_Ch14_EN_The_Pirate_Ships.mp3" },
        { photo: "images/lake-ashi.jpg",                         name: "Moto-Hakone y el Santuario",    nameEn: "Moto-Hakone Shrine",                desc: "Puerta roja flotante en el agua.",                 descEn: "Red torii floating on the water.",              fileEs: "Loop_Ch15_ES_Moto_Hakone_Santuario.mp3",               fileEn: "Loop_Ch15_EN_Moto_Hakone_Shrine.mp3" },
        { photo: "images/odawara-castle.jpg",                                                                             name: "AutobÃºs de Regreso a Odawara", nameEn: "Bus Back to Odawara",               desc: "El cÃ­rculo se cierra.",                           descEn: "The circle closes.",                            fileEs: "Loop_Ch16_ES_Autobus_Regreso_Odawara.mp3",             fileEn: "Loop_Ch16_EN_Bus_Back_Odawara.mp3" },
        { photo: "images/shinkansen.jpg",                                                                   name: "Regreso en Shinkansen",         nameEn: "Return Shinkansen",                 desc: "Hasta la prÃ³xima, Hakone.",                       descEn: "Until next time, Hakone.",                      fileEs: "Loop_Ch17_ES_Regreso_Shinkansen.mp3",                  fileEn: "Loop_Ch17_EN_Return_Shinkansen.mp3" },
      ],
    },
  },
};

// Builds the audio path from the per-stop file references.
// Bilingual tours (Hakone) use fileEs / fileEn; all others use file.
// Returns null for stops without audio yet (e.g. pending Shinjuku chapters).
window.audioPath = function (tourId, stopIndex, lang) {
  const tour = window.TOUR_DATA.tours[tourId];
  if (!tour) return null;
  const stop = tour.stops[stopIndex];
  if (!stop) return null;
  const isBilingual = tour.languages.length > 1;
  const file = isBilingual
    ? (lang === "en" ? stop.fileEn : stop.fileEs)
    : stop.file;
  if (!file) return null;
  return `audio/${tour.audioDir}/${file}`;
};

// UI translations
window.I18N = {
  es: {
    appName: "Audio GuÃ­a",
    home: "Inicio",
    destinations: "Destinos",
    tours: "Recorridos",
    stops: "paradas",
    stop: "Parada",
    of: "de",
    play: "Reproducir",
    pause: "Pausar",
    previous: "Anterior",
    next: "Siguiente",
    skipBack: "AtrÃ¡s 15s",
    skipForward: "Adelante 15s",
    settings: "Ajustes",
    language: "Idioma de la interfaz",
    spanish: "EspaÃ±ol",
    english: "English",
    audioLanguage: "Idioma del audio",
    resume: "Continuar",
    resumeFrom: "Continuar donde lo dejaste",
    startTour: "Iniciar recorrido",
    back: "Volver",
    chapters: "capÃ­tulos",
    bilingual: "BilingÃ¼e",
    spanishOnly: "Solo espaÃ±ol",
    photoHere: "FOTO AQUÃ",
    aboutResume: "Tu progreso se guarda en el dispositivo.",
    clearProgress: "Borrar progreso",
    progressCleared: "Progreso borrado",
    offlineReady: "Listo para usar sin conexiÃ³n",
    install: "Instalar app",
    audioMissing: "Audio no encontrado â€” coloca el archivo en",
    audioPending: "CapÃ­tulo pendiente â€” se aÃ±adirÃ¡ prÃ³ximamente",
  },
  en: {
    appName: "Audio Guide",
    home: "Home",
    destinations: "Destinations",
    tours: "Tours",
    stops: "stops",
    stop: "Stop",
    of: "of",
    play: "Play",
    pause: "Pause",
    previous: "Previous",
    next: "Next",
    skipBack: "Back 15s",
    skipForward: "Forward 15s",
    settings: "Settings",
    language: "Interface language",
    spanish: "EspaÃ±ol",
    english: "English",
    audioLanguage: "Audio language",
    resume: "Resume",
    resumeFrom: "Pick up where you left off",
    startTour: "Start tour",
    back: "Back",
    chapters: "chapters",
    bilingual: "Bilingual",
    spanishOnly: "Spanish only",
    photoHere: "PHOTO HERE",
    aboutResume: "Your progress is saved on this device.",
    clearProgress: "Clear progress",
    progressCleared: "Progress cleared",
    offlineReady: "Ready to use offline",
    install: "Install app",
    audioMissing: "Audio not found â€” place the file at",
    audioPending: "Chapter pending â€” coming soon",
  },
};

